#!/bin/sh

ndk=/home/matteo/android-ndk-r10e

case $AGCCARCH in
arm)	archx=arm-linux-androideabi
	bin=$archx-gcc
	flags='-mfloat-abi=softfp -march=armv7-a -mtune=cortex-a9'
	;;
arm64)
	archx=aarch64-linux-android
	bin=aarch64-linux-android-gcc
	;;
x86)	archx=x86
	bin=i686-linux-android-gcc
	flags='-march=atom'
	;;
x86_64)	archx=x86_64
	bin=x86_64-linux-android-gcc
	flags='-march=atom'
	;;
mips)	archx=mipsel-linux-android
	bin=$archx-gcc
	flags='-march=mips32r2'
	;;
mips64)	archx=mips64el-linux-android
	bin=$archx-gcc
	flags='-march=mips64r2'
	;;
esac

toolchain=$ndk/toolchains/$archx-4.9/prebuilt/linux-$(uname -m)

exec $toolchain/bin/$bin -fPIE -pie $flags --sysroot=$ndk/platforms/android-21/arch-$AGCCARCH "$@"
