#!/bin/sh

ndk=~/Android/Sdk/ndk-bundle

case $AGCCARCH in
arm)	archx=arm-linux-androideabi
	bin=$archx-gcc
	flags='-mfloat-abi=softfp -march=armv7-a -mtune=cortex-a9'
	;;
arm64)
	archx=aarch64-linux-android
	bin=aarch64-linux-android-gcc
	;;
x86)	archx=x86
	bin=i686-linux-android-gcc
	flags='-march=atom'
	;;
x86_64)	archx=x86_64
	bin=x86_64-linux-android-gcc
	flags='-march=atom'
	;;
esac

toolchain=$ndk/toolchains/$archx-4.9/prebuilt/linux-x86_64

exec $toolchain/bin/$bin -fPIE -pie $flags --sysroot=$ndk/platforms/android-28/arch-$AGCCARCH "$@"
