#!/bin/sh

ndk=/home/matteo/android-ndk-r10e

arch=$AGCCARCH

case $arch in
arm)	archx=arm-linux-androideabi
	bin=$archx-gcc
#	flags='-mfloat-abi=softfp -march=armv5te -mfpu=vfpv3-d16'
#	flags='-mfloat-abi=softfp -march=armv5te -mfpu=neon'
#	flags='-mfloat-abi=softfp -march=armv7-a -mfpu=vfpv3-d16'
	flags='-mfloat-abi=soft'
	;;
arm64)
	archx=aarch64-linux-android
	bin=aarch64-linux-android-gcc
	;;
x86)	archx=x86
	bin=i686-linux-android-gcc
	flags='-march=atom'
	;;
mips)	archx=mipsel-linux-android
	bin=$archx-gcc
	;;
esac

toolchain=$ndk/toolchains/$archx-4.9/prebuilt/linux-$(uname -m)

exec $toolchain/bin/$bin -fPIE -pie $flags --sysroot=$ndk/platforms/android-21/arch-$arch $@
