#!/bin/sh

[ $# -eq 2 ] || exec echo "Usage: $0 <install.iso> <disk.img>"

root=/tmp/${0##*/}.$$
mkdir $root
sudo mount -r -oloop "$1" $root
kvm -m 512 -no-reboot -nographic -boot d -cdrom "$1" -drive "file=$2,index=0,media=disk,format=raw" -kernel $root/install.*/vmlinuz -initrd $root/install.*/initrd.gz -append console=ttyS0
sudo umount $root
rmdir $root
