#!/bin/sh

src=/tmp/remp4-src-$$.mp4
tmp=/tmp/remp4-$$.264

# MP4Box fails to handle path with spaces
mv -f "$1" $src

oldsize=$(stat $src --printf=%s)

trackid=$(MP4Box -info $src 2>&1 |awk '/TrackID/{track=$3};/H264/{print track}')

x264encopts='crf=24'
fps=30

vf='scale=-10:720'

mencoder $src $vf -fps 30 -nosound -vf $vf,harddup -ovc x264 -o $tmp -of rawvideo -x264encopts $x264encopts

MP4Box -rem 1 $src
MP4Box -add $tmp $src

newsize=$(stat $tmp --printf=%s)

if [ $((newsize * 11)) -lt $((oldsize * 10)) ]; then
	rm $tmp
	mv $src "$1"
else
	mv $tmp "$1"
fi