#!/bin/sh

# taken from http://dev.gentoo.org/~vapier/clean-patches

[ $# -gt 0 ] && i=-i

exec sed $i \
	-e '/^index /d' \
	-e '/^new file mode /d' \
	-e '/^Index:/d' \
	-e '/^=========/d' \
	-e '/^RCS file:/d' \
	-e '/^retrieving/d' \
	-e '/^diff/d' \
	-e '/^Files .* differ$/d' \
	-e '/^Only in /d' \
	-e '/^Common subdirectories/d' \
	-e '/^deleted file mode [0-9]*$/d' \
	-e '/^Binary files .* differ/d' \
	-e '/^+++/s:\t.*::' \
	-e '/^---/s:\t.*::' \
	-e 's/^--- [^/]*\//--- a\//' \
	-e 's/^+++ [^/]*\//+++ b\//' \
	"$@"
