#!/bin/sh

# Taken from http://dev.gentoo.org/~vapier/clean-patches
# Adapted by me for gsed compatibility
# added binary files and stript first path element by teknoraver

exec sed $sedopt \
	-e '/^index /d' \
	-e '/^new file mode /d' \
	-e '/^Index:/d' \
	-e '/^=========/d' \
	-e '/^RCS file:/d' \
	-e '/^retrieving/d' \
	-e '/^diff/d' \
	-e '/^Files .* differ$/d' \
	-e '/^Only in /d' \
	-e '/^Common subdirectories/d' \
	-e '/^+++/s:\t.*::' \
	-e '/^---/s:\t.*::' \
	-e '/^+++/s:^+++ [^/]*/:+++ b/:' \
	-e '/^---/s:^--- [^/]*/:--- a/:' \
	-e '/^Binary files .* and .* differ$/d' \
	"${@}"
