#!/bin/sh
### BEGIN INIT INFO
# Provides:          dropbox
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dropbox Sync
### END INIT INFO

exec su - dropbox -c "dropbox.py $1"
